[mongodb]
roboshop.mongodb.asleanings.online

[redis]
roboshop.redis.asleanings.online

[mysql]
roboshop.mysql.asleanings.online

[rabbitmq]
roboshop.rabbitmq.asleanings.online

[catalogue]
roboshop.catalogue.asleanings.online

[user]
roboshop.user.asleanings.online

[cart]
roboshop.cart.asleanings.online

[shipping]
roboshop.shipping.asleanings.online

[payment]
roboshop.payment.asleanings.online

[frontend]
roboshop.asleanings.online

[dispatch]
roboshop.dispatcher.asleanings.online
