[mongodb]
roboshop.mongodb.aslearnings.online

[redis]
roboshop.redis.aslearnings.online

[mysql]
roboshop.mysql.aslearnings.online

[rabbitmq]
roboshop.rabbitmq.aslearnings.online

[catalogue]
roboshop.catalogue.aslearnings.online

[user]
roboshop.user.aslearnings.online

[cart]
roboshop.cart.aslearnings.online

[shipping]
roboshop.shipping.aslearnings.online

[payment]
roboshop.payment.aslearnings.online

[frontend]
roboshop.aslearnings.online

[dispatch]
roboshop.dispatcher.aslearnings.online
